import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/component/layout/providers';
import MainLayout from '@/component/layout/main-layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <MainLayout> */}
          {children}
          {/* </MainLayout> */}
        </Providers>
      </body>
    </html>
  );
}
